# Generated by Django 4.2.6 on 2023-11-08 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('comments', '0002_rename_shelter_applicationcomment_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcomment',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.shelter'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.shelter'),
        ),
        migrations.AlterField(
            model_name='sheltercomment',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.shelter'),
        ),
    ]
