# Generated by Django 4.2.4 on 2023-11-09 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_owner_application_shelter'),
        ('accounts', '0001_initial'),
        ('comments', '0002_rename_shelter_applicationcomment_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcomment',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application'),
        ),
        migrations.AlterField(
            model_name='sheltercomment',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.shelter'),
        ),
    ]
