# Generated by Django 4.2.6 on 2023-11-09 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('pet_listing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petlisting',
            name='owner',
        ),
        migrations.AddField(
            model_name='petlisting',
            name='shelter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.shelter'),
            preserve_default=False,
        ),
    ]
