# Generated by Django 4.2.6 on 2023-11-08 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('pet_listing', '0003_alter_petlisting_behavior_aggresive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlisting',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.shelter'),
        ),
    ]
