# Generated by Django 4.2.6 on 2023-11-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_listing', '0005_alter_petlisting_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlisting',
            name='age',
            field=models.IntegerField(),
        ),
    ]
